from io import BytesIO

from fpdf import FPDF
from docx import Document
from docx.shared import Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH


def sanitize_text(text: str) -> str:
    replacements = {
        "\u2018": "'",
        "\u2019": "'",
        "\u201c": '"',
        "\u201d": '"',
        "\u2013": "-",
        "\u2014": "-",
        "\u2026": "...",
        "\u00a0": " ",
        "\u20b9": "Rs.",
    }

    for old, new in replacements.items():
        text = text.replace(old, new)

    return text


def format_docx(content: str, document_type: str = "") -> bytes:
    document = Document()

    section = document.sections[0]
    section.top_margin = 720000
    section.bottom_margin = 720000
    section.left_margin = 900000
    section.right_margin = 900000

    style = document.styles["Normal"]
    style.font.name = "Times New Roman"
    style.font.size = Pt(12)

    # ---------------------------------------------------------
    # TITLE
    # ---------------------------------------------------------

    title = document.add_paragraph()
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER

    run = title.add_run("LEGAL EASE TN")
    run.bold = True
    run.font.name = "Times New Roman"
    run.font.size = Pt(16)

    # ---------------------------------------------------------
    # DOCUMENT CONTENT
    # ---------------------------------------------------------

    for index, line in enumerate(content.splitlines()):
        line = line.strip()

        if not line:
            continue

        paragraph = document.add_paragraph()

        run = paragraph.add_run(line)
        run.font.name = "Times New Roman"
        run.font.size = Pt(12)

        if (
            index < 4
            or line[:2].isdigit()
            or line.startswith("1.")
            or line.startswith("2.")
            or line.startswith("3.")
            or line.startswith("4.")
            or line.startswith("5.")
            or line.startswith("6.")
            or line.startswith("7.")
            or line.startswith("8.")
        ):
            run.bold = True

    # ---------------------------------------------------------
    # FOOTER
    # ---------------------------------------------------------

    footer = section.footer.paragraphs[0]
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER

    footer_run = footer.add_run("Generated by LegalEase TN")
    footer_run.font.name = "Times New Roman"
    footer_run.font.size = Pt(9)

    output = BytesIO()
    document.save(output)

    return output.getvalue()


def format_pdf(content: str, document_type: str = "") -> bytes:
    pdf = FPDF()

    pdf.set_auto_page_break(
        auto=True,
        margin=20
    )

    pdf.add_page()

    # ---------------------------------------------------------
    # PAGE WIDTH
    # ---------------------------------------------------------

    page_width = pdf.w - pdf.l_margin - pdf.r_margin

    # ---------------------------------------------------------
    # TITLE
    # ---------------------------------------------------------

    pdf.set_font(
        "Helvetica",
        "B",
        16
    )

    pdf.set_x(pdf.l_margin)

    pdf.multi_cell(
        page_width,
        9,
        "LEGAL EASE TN",
        align="C"
    )

    pdf.ln(3)

    # ---------------------------------------------------------
    # DOCUMENT TYPE
    # ---------------------------------------------------------

    if document_type:
        pdf.set_font(
            "Helvetica",
            "B",
            13
        )

        pdf.set_x(pdf.l_margin)

        pdf.multi_cell(
            page_width,
            8,
            sanitize_text(document_type),
            align="C"
        )

        pdf.ln(5)

    # ---------------------------------------------------------
    # SAFE TEXT WRITER
    # ---------------------------------------------------------

    def write_safe_line(text: str):
        """
        Safely writes text to the PDF.

        Uses explicit page width and character-level
        wrapping for long tokens so FPDF does not
        raise the horizontal-space error.
        """

        if not text:
            return

        words = text.split(" ")

        current_line = ""

        for word in words:

            if not word:
                continue

            # -------------------------------------------------
            # NORMAL WORD
            # -------------------------------------------------

            word_width = pdf.get_string_width(word)

            if word_width <= page_width:

                if current_line:
                    test_line = current_line + " " + word
                else:
                    test_line = word

                if pdf.get_string_width(test_line) <= page_width:
                    current_line = test_line

                else:
                    if current_line:
                        pdf.set_x(pdf.l_margin)

                        pdf.multi_cell(
                            page_width,
                            6,
                            current_line
                        )

                    current_line = word

                continue

            # -------------------------------------------------
            # LONG WORD
            # -------------------------------------------------

            if current_line:
                pdf.set_x(pdf.l_margin)

                pdf.multi_cell(
                    page_width,
                    6,
                    current_line
                )

                current_line = ""

            remaining = word

            while remaining:

                chunk = ""

                for character in remaining:

                    test_chunk = chunk + character

                    if pdf.get_string_width(test_chunk) < page_width:
                        chunk = test_chunk

                    else:
                        break

                # -------------------------------------------------
                # SAFETY FALLBACK
                # -------------------------------------------------

                if not chunk:
                    chunk = remaining[0]

                remaining = remaining[len(chunk):]

                if remaining:

                    pdf.set_x(pdf.l_margin)

                    pdf.multi_cell(
                        page_width,
                        6,
                        chunk
                    )

                else:
                    current_line = chunk

        # -----------------------------------------------------
        # REMAINING TEXT
        # -----------------------------------------------------

        if current_line:

            pdf.set_x(pdf.l_margin)

            pdf.multi_cell(
                page_width,
                6,
                current_line
            )

    # ---------------------------------------------------------
    # DOCUMENT CONTENT
    # ---------------------------------------------------------

    safe_content = sanitize_text(content)

    for raw_line in safe_content.splitlines():

        line = raw_line.strip()

        # Empty line
        if not line:
            pdf.ln(3)
            continue

        # -----------------------------------------------------
        # HEADING DETECTION
        # -----------------------------------------------------

        is_heading = (
            (
                len(line) >= 2
                and line[0].isdigit()
                and "." in line[:3]
            )
            or (
                line.isupper()
                and len(line) < 100
            )
        )

        pdf.set_font(
            "Helvetica",
            "B" if is_heading else "",
            11
        )

        write_safe_line(line)

    # ---------------------------------------------------------
    # FOOTER
    # ---------------------------------------------------------

    pdf.set_y(-15)

    pdf.set_x(pdf.l_margin)

    pdf.set_font(
        "Helvetica",
        "",
        8
    )

    pdf.cell(
        page_width,
        8,
        "Generated by LegalEase TN",
        align="C"
    )

    # ---------------------------------------------------------
    # RETURN PDF
    # ---------------------------------------------------------

    return bytes(pdf.output())